package ${config.outputpackage}.constants;


/**
 * 常量信息
 * @author generated by hfree
 * @date ${time}
 */
@Getter
@AllArgsConstructor
public ${name}Constant {

	/**
	 * 1是0否
	 */
	public static class YesNo{
		/** 是*/
    	public final static String YES = "1";
    	/** 否*/
    	public final static String NO = "0";
    }
    
}
 

