package ${config.outputpackage}.service;

import java.util.List;

import com.alibaba.fastjson.JSONObject;
import com.insigma.framework.exception.AppException;

import ${config.outputpackage}.dao.${entity};

/**
 * 
 * @author generated by hfree
 * @date ${time}
 */
public interface ${name}Service {

${content}

}
